# Generated by Django 5.0.7 on 2024-07-19 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=8)),
                ('product_name', models.CharField(max_length=8)),
                ('quantity_per_unit', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unit_in_stock', models.IntegerField()),
                ('unit_order', models.IntegerField()),
                ('re_order_level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(max_length=10)),
                ('order_quantity', models.IntegerField()),
                ('name', models.CharField(max_length=7)),
                ('order_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('order_discount', models.IntegerField()),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faith1.category')),
                ('Customers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faith1.customers')),
                ('Products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faith1.products')),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=50)),
                ('postal_code', models.IntegerField()),
                ('contact_number', models.CharField(max_length=20)),
                ('contact_title', models.CharField(max_length=20)),
                ('items', models.CharField(max_length=10)),
                ('home_page', models.CharField(max_length=10)),
                ('company_name', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=10)),
                ('county', models.CharField(max_length=10)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faith1.products')),
            ],
        ),
    ]
